# Generated by Django 4.0.3 on 2022-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, verbose_name='SYMBOL')),
                ('name_of_company', models.CharField(max_length=255, verbose_name='NAME OF COMPANY')),
                ('series', models.CharField(max_length=255, verbose_name='SERIES')),
                ('date_of_listing', models.CharField(max_length=255, verbose_name='DATE OF LISTING')),
                ('paid_up_value', models.IntegerField(verbose_name='PAID UP VALUE')),
                ('market_value', models.IntegerField(verbose_name='MARKET VALUE')),
                ('isin_number', models.CharField(max_length=255, verbose_name='ISIN NUMBER')),
                ('face_value', models.IntegerField(verbose_name='FACE VALUE')),
            ],
        ),
    ]
