# Generated by Django 4.0.3 on 2022-03-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_remove_equity_id_alter_equity_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='isin_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ISIN NUMBER'),
        ),
        migrations.AlterField(
            model_name='equity',
            name='symbol',
            field=models.CharField(max_length=255, verbose_name='SYMBOL'),
        ),
    ]
