# Generated by Django 4.0.3 on 2022-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_alter_equity_isin_number_alter_equity_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equity',
            name='isin_number',
            field=models.CharField(max_length=255, verbose_name='ISIN NUMBER'),
        ),
    ]
