# Generated by Django 4.0.3 on 2022-03-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_alter_equity_paid_up_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=255, verbose_name='SYMBOL')),
                ('series', models.CharField(max_length=255, verbose_name='SERIES')),
                ('open', models.FloatField(verbose_name='OPEN')),
                ('high', models.FloatField(verbose_name='HIGH')),
                ('low', models.FloatField(verbose_name='LOW')),
                ('close', models.FloatField(verbose_name='CLOSE')),
                ('last', models.FloatField(verbose_name='LAST')),
                ('prevclose', models.FloatField(verbose_name='PREVCLOSE')),
                ('tottrdqty', models.FloatField(verbose_name='TOTTRDQTY')),
                ('tottrdval', models.CharField(max_length=255, verbose_name='TOTTRDVAL')),
                ('timestamp', models.DateField(default='########', verbose_name='TIMESTAMP')),
                ('totaltrades', models.IntegerField(default=0, verbose_name='TOTALTRADES')),
                ('isin', models.CharField(max_length=255, verbose_name='ISIN')),
            ],
        ),
    ]
